# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Stable Release

on:
  workflow_dispatch:
  
jobs:
  release:
    runs-on: windows-latest

    steps:
    - name: Validate branch name
      id: config
      shell: pwsh
      run: |
        $branchName = "${{ github.ref_name }}"
        if ($branchName -notmatch "release/(\d+)\.(\d+)\.(\d+)") {
          Write-Host "Invalid branch name: ${{ github.ref_name }}. Use like release/1.2.3"
          exit 1
        }
        $version = $branchName.Replace("release/", "")
        Write-Host "version=$version"
        echo "version=$version" >> $env:GITHUB_OUTPUT

        $tag = "v$version"
        Write-Host "tag=$tag"
        echo "tag=$tag" >> $env:GITHUB_OUTPUT

        $zipFileName = "wimygit-$tag.zip"
        Write-Host "zipFileName=$zipFileName"
        echo "zipFileName=$zipFileName" >> $env:GITHUB_OUTPUT

    - uses: actions/checkout@v4
      with:
        ref: ${{ github.ref_name }}
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x

    - name: Configure Git User
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'

    - name: Set Official Version
      id: newVersion
      run: |
        powershell ./cicd/SetVersion.ps1 -NewVersion ${{ steps.config.outputs.version }}
        git add .
        git commit -m "Update Version to ${{ steps.config.outputs.version }}"
        git push origin ${{ github.ref_name }}
        
    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: DotNet Publish
      run: dotnet publish WimyGit -c Release /p:PublishProfile=ReleasePublishProfile

    - name: Create tag
      id: tag
      run: |
        git tag ${{ steps.config.outputs.tag }} --force
        git push origin ${{ steps.config.outputs.tag }} --force

    - name: Zip build folder
      shell: pwsh
      run: |
        powershell Compress-Archive -Path WimyGit\bin\Release\publish\* -DestinationPath ${{ steps.config.outputs.zipFileName }} -Force

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        name: "WimyGit ${{ steps.config.outputs.tag }}"
        tag_name: ${{ steps.config.outputs.tag }}
        files: ${{ steps.config.outputs.zipFileName }}
        generate_release_notes: true
        prerelease: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Winget Publish
      env:
        GITHUB_TOKEN: ${{ secrets.MY_PAT }}
      shell: pwsh
      run: |
        $packageIdentifier = "Wimysoft.WimyGit"
        $newVersion = "${{ steps.config.outputs.version }}"
        $newDownloadUrl = "https://github.com/zelon/wimygit/releases/download/${{ steps.config.outputs.tag }}/${{ steps.config.outputs.zipFileName }}"
        Write-Host "-packageIdentifier $packageIdentifier -newVersion $newVersion -newDownloadUrl $newDownloadUrl"
        powershell .\cicd\CreateWingetPullRequest.ps1 submit -packageIdentifier $packageIdentifier -newVersion $newVersion -newDownloadUrl $newDownloadUrl -token $env:GITHUB_TOKEN
        
