# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Stable Release

on:
  workflow_dispatch:
    inputs:
      winget-publish:
        description: 'Publish to winget'
        type: boolean
        default: true  

jobs:
  release:
    runs-on: windows-latest

    steps:
    - name: Validate branch name and set variables
      id: config
      shell: pwsh
      run: |
        $branchName = "${{ github.ref_name }}"
        if ($branchName -notmatch "release/(\d+)\.(\d+)\.(\d+)") {
          Write-Host "Invalid branch name: ${{ github.ref_name }}. Use like release/1.2.3"
          exit 1
        }
        $version = $branchName.Replace("release/", "")
        Write-Host "version=$version"
        echo "version=$version" >> $env:GITHUB_OUTPUT

        $tag = "v$version"
        Write-Host "tag=$tag"
        echo "tag=$tag" >> $env:GITHUB_OUTPUT

        $zipFileName = "wimygit-$tag.zip"
        Write-Host "zipFileName=$zipFileName"
        echo "zipFileName=$zipFileName" >> $env:GITHUB_OUTPUT

        $zipDownloadUrl = "https://github.com/zelon/wimygit/releases/download/$tag/$zipFileName"
        Write-Host "zipDownloadUrl=$zipDownloadUrl"
        echo "zipDownloadUrl=$zipDownloadUrl" >> $env:GITHUB_OUTPUT

    - uses: actions/checkout@v6
      with:
        ref: ${{ github.ref_name }}
    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 10.0.x

    - name: Configure Git User
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'

    - name: Set Official Version
      shell: pwsh
      run: |
        ./cicd/SetVersion.ps1 -NewVersion ${{ steps.config.outputs.version }}
        git add .
        git commit -m "Update Version to ${{ steps.config.outputs.version }}"
        git push origin ${{ github.ref_name }}
        
    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: DotNet Publish
      run: dotnet publish WimyGit -c Release /p:PublishProfile=ReleasePublishProfile

    - name: Create tag
      id: tag
      run: |
        git tag ${{ steps.config.outputs.tag }} --force
        git push origin ${{ steps.config.outputs.tag }} --force

    - name: Zip build folder
      shell: pwsh
      run: |
        Compress-Archive -Path WimyGit\bin\Release\publish\* -DestinationPath ${{ steps.config.outputs.zipFileName }} -Force

    - name: Create GitHub Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        $tag = "${{ steps.config.outputs.tag }}"
        $zipName = "${{ steps.config.outputs.zipFileName }}"
        $title = "WimyGit ${{ steps.config.outputs.tag }}"
        gh release create $tag $zipName --generate-notes --prerelease --title $title

    - name: Winget Publish
      if: ${{ inputs.winget-publish == true }}
      env:
        GITHUB_TOKEN: ${{ secrets.MY_PAT }}
      shell: pwsh
      run: |
        $packageIdentifier = "Wimysoft.WimyGit"
        $newVersion = "${{ steps.config.outputs.version }}"
        $newDownloadUrl = "${{ steps.config.outputs.zipDownloadUrl }}"
        Write-Host "-packageIdentifier $packageIdentifier -newVersion $newVersion -newDownloadUrl $newDownloadUrl"
        .\cicd\CreateWingetPullRequest.ps1 submit -packageIdentifier $packageIdentifier -newVersion $newVersion -newDownloadUrl $newDownloadUrl -token $env:GITHUB_TOKEN
        
